package view;

import javax.swing.JOptionPane;
import model.Jogador;

public class Menu extends javax.swing.JFrame {

    Jogador jogador1 = new Jogador();
    Jogador jogador2 = new Jogador();

    public Menu(Jogador jogador) {
        this.jogador1 = jogador;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        rb1Jogador.setSelected(true);
        rbFacil.setSelected(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgQtdJogadores = new javax.swing.ButtonGroup();
        rbgDificuldade = new javax.swing.ButtonGroup();
        lblQtdJogadores = new javax.swing.JLabel();
        lblDificuldade = new javax.swing.JLabel();
        btnAjuda = new javax.swing.JButton();
        btnJogar = new javax.swing.JButton();
        rb1Jogador = new javax.swing.JRadioButton();
        rb2Jogadores = new javax.swing.JRadioButton();
        rbFacil = new javax.swing.JRadioButton();
        rbMedio = new javax.swing.JRadioButton();
        rbDificil = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQtdJogadores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQtdJogadores.setText("Qtd de Jogadores:");

        lblDificuldade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDificuldade.setText("Dificuldade:");

        btnAjuda.setText("Ajuda");
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });

        btnJogar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        rbgQtdJogadores.add(rb1Jogador);
        rb1Jogador.setText("1 Jogador");
        rb1Jogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1JogadorActionPerformed(evt);
            }
        });

        rbgQtdJogadores.add(rb2Jogadores);
        rb2Jogadores.setText("2 Jogadores");

        rbgDificuldade.add(rbFacil);
        rbFacil.setText("Fácil");

        rbgDificuldade.add(rbMedio);
        rbMedio.setText("Médio");

        rbgDificuldade.add(rbDificil);
        rbDificil.setText("Difícil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDificuldade)
                            .addComponent(lblQtdJogadores))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb1Jogador)
                                .addGap(18, 18, 18)
                                .addComponent(rb2Jogadores))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbFacil)
                                .addGap(18, 18, 18)
                                .addComponent(rbMedio)
                                .addGap(18, 18, 18)
                                .addComponent(rbDificil)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdJogadores)
                    .addComponent(rb1Jogador)
                    .addComponent(rb2Jogadores))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDificuldade)
                    .addComponent(rbFacil)
                    .addComponent(rbMedio)
                    .addComponent(rbDificil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjuda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        new Ajuda();
    }//GEN-LAST:event_btnAjudaActionPerformed

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        
        if (rb1Jogador.isSelected()) {
            
            if (rbFacil.isSelected()) {
                new ContainerJanelas(jogador1,jogador2, 1, false);
                this.dispose();
            }
            if (rbMedio.isSelected()) {
                new ContainerJanelas(jogador1,jogador2, 2, false);
                this.dispose();
            }
            if (rbDificil.isSelected()) {
                new ContainerJanelas(jogador1,jogador2, 3, false);
                this.dispose();
            }
        } else if(rb2Jogadores.isSelected()){
            JOptionPane.showMessageDialog(null, "Antes de continuar deve-se logar o Jogador 2");
            if (rbFacil.isSelected()) {                
                new Login2(jogador1, 1, true);
                this.dispose();
            }
            if (rbMedio.isSelected()) {
                new Login2(jogador1, 2, true);
                this.dispose();
            }
            if (rbDificil.isSelected()) {
                new Login2(jogador1, 2, true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    private void rb1JogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1JogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1JogadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jogador jogador = null;
                new Menu(jogador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnJogar;
    private javax.swing.JLabel lblDificuldade;
    private javax.swing.JLabel lblQtdJogadores;
    private javax.swing.JRadioButton rb1Jogador;
    private javax.swing.JRadioButton rb2Jogadores;
    private javax.swing.JRadioButton rbDificil;
    private javax.swing.JRadioButton rbFacil;
    private javax.swing.JRadioButton rbMedio;
    private javax.swing.ButtonGroup rbgDificuldade;
    private javax.swing.ButtonGroup rbgQtdJogadores;
    // End of variables declaration//GEN-END:variables
}
